---
overwrite: true
prefer_grub_d: true
keepDistributor: true
kernel_params: [ "quiet" ]
defaults:
   GRUB_TIMEOUT: 5
   GRUB_DEFAULT: "saved"
   GRUB_DISABLE_SUBMENU: true
   GRUB_DISABLE_RECOVERY: true
   GRUB_DISTRIBUTOR: "ZarchBlack"
   GRUB_THEME: "/usr/share/grub/themes/ZeroLayan/theme.txt"
always_use_defaults: false
