---
i18n:
    name: "Preparing Kernel and Initcpio"

dontChroot: false
timeout: 999
script:
    - "-rm /etc/mkinitcpio.conf.d/archiso.conf"
    - "-cp /etc/mkinitcpio.conf.new /etc/mkinitcpio.conf"
    - "-/usr/local/bin/fix-btrfs-boot.sh"
