---
i18n:
  name: "Finalizing ZarchBlack installation"
dontChroot: false
timeout: 999
script:
  - "-rm /var/lib/pacman/db.lck"
  - "-mv /etc/systemd/system/pacman-init /etc/systemd/system/pacman-init.service"
  - "-rm /etc/systemd/system/etc-pacman.d-gnupg.mount"
  - "-pacman -Rs --noconfirm calamares archinstall livecd-sounds"
  - "-pacman-key --init"
  - "-pacman-key --populate archlinux"
  - "-pacman-key --add /etc/pacman.d/zarchblack.gpg"
  - "-pacman-key --lsign-key security@zarchblack.org"
  - "-rm -f /home/*/.config/autostart/calamares.desktop"
  - "-rm -f /usr/share/applications/calamares.desktop"
  - "-rm -f /etc/sddm.conf.d/autologin.conf"
  - "-pacman -Rdd --noconfirm plasma-welcome"
  - "-plymouth-set-default-theme -R zarchblack"
  - "-flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"
