#!/bin/bash
# ===================================================================
# ZarchBlack — Package List Generator
# Merges all files in iso/package-lists/ into iso/packages.x86_64
# Usage: ./scripts/generate-packages.sh
# ===================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
LISTS_DIR="$ROOT_DIR/iso/package-lists"
OUTPUT_FILE="$ROOT_DIR/iso/packages.x86_64"

if [ ! -d "$LISTS_DIR" ]; then
    echo "❌ Error: package-lists directory not found at $LISTS_DIR"
    exit 1
fi

echo "=== ZarchBlack Package List Generator ==="
echo "Source: $LISTS_DIR"
echo "Output: $OUTPUT_FILE"
echo ""

# Write header
cat > "$OUTPUT_FILE" << 'HEADER'
# ===================================================================
#                           ZarchBlack
#         KDE Plasma Edition - x86_64 Package Manifest
# ===================================================================
# AUTO-GENERATED by scripts/generate-packages.sh
# Do NOT edit this file directly — edit files in iso/package-lists/
# ===================================================================
HEADER

# Process each list file in alphabetical order
TOTAL=0
for list_file in "$LISTS_DIR"/*.txt; do
    if [ -f "$list_file" ]; then
        section=$(basename "$list_file" .txt)
        count=$(grep -cv '^\s*#\|^\s*$' "$list_file" 2>/dev/null || echo 0)
        echo "  📦 Adding: $section ($count packages)"
        echo "" >> "$OUTPUT_FILE"
        echo "# === $(echo "$section" | tr '[:lower:]' '[:upper:]') ===" >> "$OUTPUT_FILE"
        cat "$list_file" >> "$OUTPUT_FILE"
        TOTAL=$((TOTAL + count))
    fi
done

echo ""
echo "✅ Generated $OUTPUT_FILE"
echo "   Total packages: $TOTAL"
